[package]
name = "polycube-enum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
tokio = { version = "1.29.1", features = ["full"] }
sha1 = "0.10.5"
